apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: gcr.io/my-kubernetetes/demo-webserver-image:latest
        ports:
        - containerPort: 8080
      #   volumeMounts:
      #   - name: gcsfuse-html-volume
      #     mountPath: /usr/share/nginx/html 
      #     readOnly: true
      # serviceAccountName: demo-gke-service-account
      # imagePullSecrets:
      # - name: gcr-json-key
      # volumes:
      # - name: gcsfuse-html-volume
      #   csi:
      #     driver: gcsfuse.csi.storage.gke.io
      #     volumeAttributes:
      #       bucketName: demo-app-bucket-ia
      #       mountOptions: "implicit-dirs"