apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: demo
  # annotations:
  #   gke-gcsfuse/volumes: "true"
  #   gke-gcsfuse/cpu-limit: "1"
  #   gke-gcsfuse/memory-limit: 500m
  #   # gke-gcsfuse/ephemeral-storage-limit: 10Gi
  #   gke-gcsfuse/cpu-request: 200m
  #   gke-gcsfuse/memory-request: 128m
    # gke-gcsfuse/ephemeral-storage-request: 5Gi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      gke-gcsfuse/volumes: "true"
      labels:
        app: webserver
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: webserver
        image: gcr.io/my-kubernetetes/demo-webserver-image:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: gcsfuse-html-volume
          mountPath: /usr/share/nginx/html 
          readOnly: true
      serviceAccountName: demo-gke-service-account
      imagePullSecrets:
      - name: gcr-json-key
      volumes:
      - name: gcsfuse-html-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: demo-app-bucket-ia
            mountOptions: "implicit-dirs"