apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: demo
spec:
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer