apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-web-server
  namespace: argocd
spec:
  project: demo-proj
  source:
    repoURL: 'https://github.com/Antonyhoainam/gcp-personal-project.git'
    targetRevision: HEAD
    path: 'manual/app/gke/components'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true