steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-webserver-image:latest', '.']
images:
  - 'gcr.io/$PROJECT_ID/demo-webserver-image:latest'
substitutions:
  _PROJECT_ID: 'my-kubernetes'