steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-webserver-image:latest', '.']
images:
  - 'gcr.io/$PROJECT_ID/demo-webserver-image:latest'
substitutions:
  _PROJECT_ID: 'my-kubernetes'
options:
  logging: CLOUD_LOGGING_ONLY
  # This option specifies that only Cloud Logging should be used for logging.